apiVersion: v2
description: >
  Helm chart for samer-agent
  capabilities for the Qlik.
name: samer-agent
version: 0.1.1
keywords:
  - samer-agent
home: https://www.qlik.com
sources:
  - https://github.com/qlik-trial/samer-agent
dependencies:
  - name: qlikcommon
    version: 3.26.2
    repository: oci://ghcr.io/qlik-trial/helm
    condition: global.component-common-imports
