apiVersion: qlik.com/v1
kind: HelmChart
metadata:
  name: samer-agent
chartHome: ../chart
chartName: samer-agent
releaseName: samer-agent
releaseNamespace: $(NAMESPACE)
newChartVersion: $(VERSION)
values:
  image:
    tag: $(VERSION)
